name: Build and Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build and Publish macOS
        if: matrix.os == 'macos-latest'
        run: npx electron-builder --mac -p always -c.extraMetadata.main=main.js
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Publish Windows
        if: matrix.os == 'windows-latest'
        run: npx electron-builder --win -p always -c.extraMetadata.main=main.js
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
